// store/slices/sectionsSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Initial state for the form sections
const initialState = {
  npi: "",
  cmsCertificationNumber: "",
  branchState: "",
  branchIdNumber: "",
  patientIdNumber: "",
  startOfCareDate: "",
  resumptionOfCareDate: "",
  patientFirstName: "",
  patientMiddleInitial: "",
  patientLastName: "",
  patientSuffix: "",
  patientStateOfResidence: "",
  patientZipCode: "",
  socialSecurityNumber: "",
  medicareNumber: "",
  medicaidNumber: "",
  gender: "",
  birthDate: "",
  ethnicity: [],
  race: [],
  paymentSources: [],
  preferredLanguage: "",
  needInterpreter: "",
  disciplineOfPersonCompletingAssessment: "",
  dateAssessmentCompleted: "",
  reasonForAssessment: "",
  dischargeTransferDeathDate: "",
  dateOfPhysicianOrderedSOC: "",
  dateOfReferral: "",
  transportation: [],
  inpatientFacilityDischargedFrom: [],
  inpatientDischargeDate: "",
  emergentCare: "",
  reasonForEmergentCare: [],
  inpatientFacilityAdmittedTo: "",
  dischargeDisposition: "",
  medicationListProvided: "",
  routeMedicationListTransmission: [],
  medicationListProvidedToPatient: "",
  routeMedicationListTransmissionToPatient: "",
  hearing: "",
  vision: "",
  healthLiteracy: "",
  interviewConducted: "",
  repetitionOfThreeWords: "",
  temporalOrientationYear: "",
  temporalOrientationMonth: "",
  temporalOrientationDay: "",
  recallSock: "",
  recallBlue: "",
  recallBed: "",
  bimsSummaryScore: "",
  deliriumMentalStatusChange: "",
  deliriumInattention: "",
  deliriumDisorganizedThinking: "",
  deliriumAlteredConsciousness: "",
  cognitiveFunctioning: "",
  whenConfused: "",
  whenAnxious: "",
  patientMoodUnderstood: "",
  littleInterestPresence: "",
  littleInterestFrequency: "",
  feelingDownPresence: "",
  feelingDownFrequency: "",
  troubleSleepingPresence: "",
  troubleSleepingFrequency: "",
  feelingTiredPresence: "",
  feelingTiredFrequency: "",
  poorAppetitePresence: "",
  poorAppetiteFrequency: "",
  feelingBadPresence: "",
  feelingBadFrequency: "",
  troubleConcentratingPresence: "",
  troubleConcentratingFrequency: "",
  movingSlowlyPresence: "",
  movingSlowlyFrequency: "",
  thoughtsOfHarmingPresence: "",
  thoughtsOfHarmingFrequency: "",
  totalSeverityScore: "",
  socialIsolation: "",
  memoryDeficit: false,
  impairedDecisionMaking: false,
  verbalDisruption: false,
  physicalAggression: false,
  disruptiveBehavior: false,
  delusionalBehavior: false,
  noneOfTheAbove: false,
  disruptiveBehaviorFrequency: "",
  livingArrangement: "",
  assistanceAvailability: "",
  adlAssistance: "",
  medicationAssistance: "",
  medicalProceduresAssistance: "",
  supervisionSafetyAssistance: "",
  grooming: "",
  upperBodyDressing: "",
  lowerBodyDressing: "",
  bathing: "",
  toiletTransferring: "",
  toiletingHygiene: "",
  transferring: "",
  ambulationLocomotion: "",
  gg0100: {
    selfCare: "",
    indoorMobility: "",
    stairs: "",
    functionalCognition: "",
  },
  gg0110: {
    manualWheelchair: false,
    motorizedWheelchair: false,
    mechanicalLift: false,
    walker: false,
    orthoticsProsthetics: false,
    noneOfTheAbove: false,
  },
  gg0130: {
    eating: "",
    oralHygiene: "",
    toiletingHygiene: "",
    showerBatheSelf: "",
    upperBodyDressing: "",
    lowerBodyDressing: "",
    puttingOnTakingOffFootwear: "",
  },
  gg0170: {
    rollLeftRight: "",
    sitToLying: "",
    lyingToSitting: "",
    sitToStand: "",
    chairBedToChair: "",
    toiletTransfer: "",
    carTransfer: "",
    walk10Feet: "",
    walk50FeetTwoTurns: "",
    walk150Feet: "",
    walk10FeetUnevenSurfaces: "",
    stepCurb: "",
    fourSteps: "",
    twelveSteps: "",
    pickingUpObject: "",
    usesWheelchairScooter: false,
    wheel50FeetTwoTurns: "",
    wheel150Feet: "",
  },
  m1600: "",
  m1610: "",
  m1620: "",
  m1630: "",
  primaryDiagnosis: "",
  otherDiagnoses: ["", "", "", "", "", ""],
  primaryDiagnosisRating: "",
  otherDiagnosesRatings: ["", "", "", "", "", ""],
  comorbidities: {
    pvd: false,
    dm: false,
    none: false,
  },
  riskForHospitalization: {
    falls: false,
    weightLoss: false,
    hospitalizations: false,
    emergencyVisits: false,
    declineInStatus: false,
    complianceDifficulty: false,
    medications: false,
    exhaustion: false,
    otherRisks: false,
    none: false,
  },
  painEffectOnSleep: "",
  painInterferenceWithTherapy: "",
  painInterferenceWithActivities: "",
  fallsSinceSOCROC: "",
  fallsDetails: {
    noInjury: false,
    injury: false,
    majorInjury: false,
  },
  shortOfBreath: "",
  height: "",
  weight: "",
  nutritionalApproachesOnAdmission: {
    parenteralIVFeeding: false,
    feedingTube: false,
    mechanicallyAlteredDiet: false,
    therapeuticDiet: false,
    none: false,
  },
  nutritionalApproachesLast7Days: {
    parenteralIVFeeding: false,
    feedingTube: false,
    mechanicallyAlteredDiet: false,
    therapeuticDiet: false,
    none: false,
  },
  nutritionalApproachesAtDischarge: {
    parenteralIVFeeding: false,
    feedingTube: false,
    mechanicallyAlteredDiet: false,
    therapeuticDiet: false,
    none: false,
  },
  feedingOrEating: "",
  unhealedPressureUlcer: "",
  oldestStage2PressureUlcer: "",
  numberOfStage2Ulcers: "",
  numberOfStage3Ulcers: "",
  numberOfStage4Ulcers: "",
  numberOfUnstageableDressingUlcers: "",
  numberOfUnstageableSloughUlcers: "",
  numberOfDeepTissueInjuries: "",
  numberOfStage1Injuries: "",
  mostProblematicUlcerStage: "",
  stasisUlcer: "",
  numberOfObservableStasisUlcers: "",
  mostProblematicStasisUlcerStatus: "",
  surgicalWound: "",
  mostProblematicSurgicalWoundStatus: "",
  highRiskDrugs: {
    antipsychotic: { isTaking: false, indicationNoted: false },
    anticoagulant: { isTaking: false, indicationNoted: false },
    antibiotic: { isTaking: false, indicationNoted: false },
    opioid: { isTaking: false, indicationNoted: false },
    antiplatelet: { isTaking: false, indicationNoted: false },
    hypoglycemic: { isTaking: false, indicationNoted: false },
    none: { isTaking: false },
  },
  drugRegimenReview: "",
  medicationFollowUp: "",
  medicationIntervention: "",
  highRiskDrugEducation: "",
  managementOralMedications: "",
  managementInjectableMedications: "",
  specialTreatmentsAdmission: {
    chemotherapy: false,
    radiation: false,
    oxygenTherapy: false,
    suctioning: false,
    tracheostomyCare: false,
    invasiveVentilator: false,
    nonInvasiveVentilator: false,
    ivMedications: false,
    transfusions: false,
    dialysis: false,
    ivAccess: false,
    noneOfTheAbove: false,
  },
  specialTreatmentsDischarge: {
    chemotherapy: false,
    radiation: false,
    oxygenTherapy: false,
    suctioning: false,
    tracheostomyCare: false,
    invasiveVentilator: false,
    nonInvasiveVentilator: false,
    ivMedications: false,
    transfusions: false,
    dialysis: false,
    ivAccess: false,
    noneOfTheAbove: false,
  },
  covidVaccinationUpToDate: "",
  influenzaVaccinePeriod: "",
  influenzaVaccineReceived: "",
  fallsPrevention: "",
  depressionIntervention: "",
  painIntervention: "",
  pressureUlcerPrevention: "",
  pressureUlcerTreatment: "",
};

const sectionsSlice = createSlice({
  name: "sections",
  initialState,
  reducers: {
    updateFormData: (state, action) => {
      return { ...state, ...action.payload };
    },
    resetForm: () => initialState,
  },
});

export const getAllSectionState = (state) => state.section;
export const { updateFormData, resetForm } = sectionsSlice.actions;
export default sectionsSlice.reducer;
