const test = {
    "gg0100": {
      "selfCare": "",
      "indoorMobility": "",
      "stairs": "",
      "functionalCognition": ""
    },
    "gg0110": {
      "manualWheelchair": false,
      "motorizedWheelchair": false,
      "mechanicalLift": false,
      "walker": false,
      "orthoticsProsthetics": false,
      "noneOfTheAbove": false
    },
    "gg0130": {
      "eating": "",
      "oralHygiene": "",
      "toiletingHygiene": "",
      "showerBatheSelf": "",
      "upperBodyDressing": "",
      "lowerBodyDressing": "",
      "puttingOnTakingOffFootwear": ""
    },
    "gg0170": {
      "rollLeftRight": "",
      "sitToLying": "",
      "lyingToSitting": "",
      "sitToStand": "",
      "chairBedToChair": "",
      "toiletTransfer": "",
      "carTransfer": "",
      "walk10Feet": "",
      "walk50FeetTwoTurns": "",
      "walk150Feet": "",
      "walk10FeetUnevenSurfaces": "",
      "stepCurb": "",
      "fourSteps": "",
      "twelveSteps": "",
      "pickingUpObject": "",
      "usesWheelchairScooter": false,
      "wheel50FeetTwoTurns": "",
      "wheel150Feet": ""
    },
    "highRiskDrugs": {
      "antipsychotic": {
        "isTaking": false,
        "indicationNoted": false
      },
      "anticoagulant": {
        "isTaking": false,
        "indicationNoted": false
      },
      "antibiotic": {
        "isTaking": false,
        "indicationNoted": false
      },
      "opioid": {
        "isTaking": false,
        "indicationNoted": false
      },
      "antiplatelet": {
        "isTaking": false,
        "indicationNoted": false
      },
      "hypoglycemic": {
        "isTaking": false,
        "indicationNoted": false
      },
      "none": {
        "isTaking": false
      }
    },
    "numberOfWounds": "",
    "observationOfWounds": "",
    "priorFunctionLevel": "",
    "screenCompleted": "",
    "skinTurgor": "",
    "specialInstructions": "",
    "spinalCordInjury": "",
    "transferToChairBed": "",
    "woundStatus": "",
    "_id": "66b3a4f766081944e6722a3f",
    "npi": "234324234",
    "cmsCertificationNumber": "342314",
    "branchState": "sdfsdfsadf",
    "branchIdNumber": "32532453425",
    "patientIdNumber": "23452345",
    "startOfCareDate": "2024-08-08",
    "resumptionOfCareDate": "2024-08-08",
    "patientFirstName": "Md Sajib",
    "patientMiddleInitial": "1",
    "patientLastName": "Shikder",
    "patientSuffix": "M",
    "patientStateOfResidence": "23432453",
    "patientZipCode": "12342134",
    "socialSecurityNumber": "23421341234",
    "medicareNumber": "12342134",
    "medicaidNumber": "234532453245",
    "gender": "Male",
    "birthDate": "2024-08-07T00:00:00.000Z",
    "ethnicity": [
      "Hispanic or Latino",
      "Not Hispanic or Latino"
    ],
    "race": [
      "American Indian or Alaska Native",
      "Asian",
      "Black or African American",
      "Native Hawaiian or Other Pacific Islander"
    ],
    "paymentSources": [
      "Medicare",
      "Medicaid",
      "Private Pay"
    ],
    "preferredLanguage": "Bangla",
    "needInterpreter": "Yes",
    "disciplineOfPersonCompletingAssessment": "32q4234",
    "dateAssessmentCompleted": "2024-08-15T00:00:00.000Z",
    "reasonForAssessment": "234234",
    "dischargeTransferDeathDate": "2024-08-08T00:00:00.000Z",
    "dateOfPhysicianOrderedSOC": "2024-08-14T00:00:00.000Z",
    "dateOfReferral": "2024-08-09T00:00:00.000Z",
    "transportation": [
      "Private Car",
      "Public Transportation"
    ],
    "inpatientFacilityDischargedFrom": [
      "Hospital",
      "Nursing Facility",
      "Rehabilitation Facility"
    ],
    "inpatientDischargeDate": "2024-08-15T00:00:00.000Z",
    "emergentCare": "Yes",
    "reasonForEmergentCare": [
      "Planned"
    ],
    "inpatientFacilityAdmittedTo": "demo",
    "dischargeDisposition": "asdf",
    "medicationListProvided": "Yes",
    "routeMedicationListTransmission": [
      "In-Person",
      "Mail"
    ],
    "medicationListProvidedToPatient": "Yes",
    "routeMedicationListTransmissionToPatient": [
      "In-Person",
      "Mail"
    ],
    "hearing": "0",
    "vision": "",
    "healthLiteracy": "",
    "interviewConducted": "0",
    "repetitionOfThreeWords": "0",
    "temporalOrientationYear": "0",
    "temporalOrientationMonth": "0",
    "temporalOrientationDay": "0",
    "recallSock": "0",
    "recallBlue": "0",
    "recallBed": "1",
    "bimsSummaryScore": "34345",
    "deliriumMentalStatusChange": "",
    "deliriumInattention": "",
    "deliriumDisorganizedThinking": "",
    "deliriumAlteredConsciousness": "",
    "cognitiveFunctioning": "",
    "whenConfused": "",
    "whenAnxious": "",
    "patientMoodUnderstood": "",
    "littleInterestPresence": "",
    "littleInterestFrequency": "",
    "feelingDownPresence": "",
    "feelingDownFrequency": "",
    "troubleSleepingPresence": "",
    "troubleSleepingFrequency": "",
    "feelingTiredPresence": "",
    "feelingTiredFrequency": "",
    "poorAppetitePresence": "",
    "poorAppetiteFrequency": "",
    "feelingBadPresence": "",
    "feelingBadFrequency": "",
    "troubleConcentratingPresence": "",
    "troubleConcentratingFrequency": "",
    "movingSlowlyPresence": "",
    "movingSlowlyFrequency": "",
    "thoughtsOfHarmingPresence": "",
    "thoughtsOfHarmingFrequency": "",
    "totalSeverityScore": "",
    "socialIsolation": "",
    "memoryDeficit": false,
    "impairedDecisionMaking": false,
    "verbalDisruption": false,
    "physicalAggression": false,
    "disruptiveBehavior": true,
    "delusionalBehavior": true,
    "noneOfTheAbove": false,
    "disruptiveBehaviorFrequency": "0",
    "livingArrangement": [
      "B06"
    ],
    "assistanceAvailability": "",
    "adlAssistance": "0",
    "medicationAssistance": "",
    "medicalProceduresAssistance": "",
    "supervisionSafetyAssistance": "",
    "grooming": "",
    "upperBodyDressing": "",
    "lowerBodyDressing": "",
    "bathing": "",
    "toiletTransferring": "",
    "toiletingHygiene": "",
    "transferring": "",
    "ambulationLocomotion": "",
    "m1600": "",
    "m1610": "",
    "m1620": "",
    "m1630": "",
    "primaryDiagnosis": [
      ""
    ],
    "otherDiagnoses": [
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    "primaryDiagnosisRating": "",
    "otherDiagnosesRatings": [
      "",
      "",
      "",
      "",
      "",
      ""
    ],
    "riskForHospitalization": {
      "falls": false,
      "weightLoss": false,
      "hospitalizations": false,
      "emergencyVisits": false,
      "declineInStatus": false,
      "complianceDifficulty": false,
      "medications": false,
      "exhaustion": false,
      "otherRisks": false,
      "none": false
    },
    "painEffectOnSleep": "",
    "painInterferenceWithTherapy": "",
    "painInterferenceWithActivities": "",
    "fallsSinceSOCROC": "",
    "shortOfBreath": "",
    "height": "",
    "weight": "",
    "feedingOrEating": "",
    "unhealedPressureUlcer": "",
    "oldestStage2PressureUlcer": "",
    "numberOfStage2Ulcers": "",
    "numberOfStage3Ulcers": "",
    "numberOfStage4Ulcers": "",
    "numberOfUnstageableDressingUlcers": "",
    "numberOfUnstageableSloughUlcers": "",
    "numberOfDeepTissueInjuries": "",
    "numberOfStage1Injuries": "",
    "mostProblematicUlcerStage": "",
    "stasisUlcer": "",
    "numberOfObservableStasisUlcers": "",
    "mostProblematicStasisUlcerStatus": "",
    "surgicalWound": "",
    "mostProblematicSurgicalWoundStatus": "",
    "drugRegimenReview": "",
    "medicationFollowUp": "",
    "medicationIntervention": "",
    "highRiskDrugEducation": "",
    "managementOralMedications": "",
    "managementInjectableMedications": [
      ""
    ],
    "specialTreatmentsAdmission": {
      "chemotherapy": false,
      "radiation": false,
      "oxygenTherapy": false,
      "suctioning": false,
      "tracheostomyCare": false,
      "invasiveVentilator": false,
      "nonInvasiveVentilator": false,
      "ivMedications": false,
      "transfusions": false,
      "dialysis": false,
      "ivAccess": false,
      "noneOfTheAbove": false
    },
    "specialTreatmentsDischarge": {
      "chemotherapy": false,
      "radiation": false,
      "oxygenTherapy": false,
      "suctioning": false,
      "tracheostomyCare": false,
      "invasiveVentilator": false,
      "nonInvasiveVentilator": false,
      "ivMedications": false,
      "transfusions": false,
      "dialysis": false,
      "ivAccess": false,
      "noneOfTheAbove": false
    },
    "covidVaccinationUpToDate": "",
    "influenzaVaccinePeriod": "",
    "influenzaVaccineReceived": "",
    "fallsPrevention": "",
    "depressionIntervention": "",
    "painIntervention": "",
    "pressureUlcerPrevention": "",
    "pressureUlcerTreatment": "",
    "trash": true,
    "status": true,
    "createdAt": "2024-08-07T16:46:47.300Z",
    "updatedAt": "2024-08-07T16:46:47.300Z",
    "__v": 0
  }