import { rootApi } from "../RootApi";

export const HHACarePlanApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    // Query endpoint to get a HHACarePlan record by ID
    getHHACarePlanById: builder.query({
      query: (id) => `hhacareplan/${id}`,
      providesTags: (result, error, id) => [{ type: "HHACarePlan", id }],
    }),

    // Query endpoint to get all HHACarePlan records by patient ID
    getHHACarePlansByPatientId: builder.query({
      query: (patientId) => `hhacareplan/patient/${patientId}`,
      providesTags: (result, error, patientId) => [
        { type: "PatientHHACarePlan", id: patientId },
      ],
    }),

    // Mutation endpoint to create a new HHACarePlan record
    createHHACarePlan: builder.mutation({
      query: (hhacareplanData) => ({
        url: "hhacareplan",
        method: "POST",
        body: hhacareplanData,
      }),
      invalidatesTags: [
        { type: "HHACarePlan" },
        { type: "PatientHHACarePlan" },
      ],
    }),

    // Mutation endpoint to update an existing HHACarePlan record
    updateHHACarePlan: builder.mutation({
      query: ({ id, hhacareplanData }) => ({
        url: `hhacareplan/${id}`,
        method: "PUT",
        body: hhacareplanData,
      }),
      invalidatesTags: (result, error, { id }) => [
        { type: "HHACarePlan", id },
        { type: "PatientHHACarePlan", id: result?.patientId }, // Assuming result includes patientId
      ],
    }),

    // Mutation endpoint to delete a HHACarePlan record
    deleteHHACarePlan: builder.mutation({
      query: (id) => ({
        url: `hhacareplan/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, id) => [
        { type: "HHACarePlan", id },
        { type: "PatientHHACarePlan", id: result?.patientId }, // Assuming result includes patientId
      ],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetHHACarePlanByIdQuery,
  useGetHHACarePlansByPatientIdQuery,
  useCreateHHACarePlanMutation,
  useUpdateHHACarePlanMutation,
  useDeleteHHACarePlanMutation,
} = HHACarePlanApi;
