import { rootApi } from "../RootApi";

export const TenDaySummaryCaseConferenceApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    // Query endpoint to get a ten-day summary by ID
    getTenDaySummaryCaseConferenceById: builder.query({
      query: (summaryId) => `tendaysummarycaseconference/${summaryId}`,
      providesTags: (result, error, summaryId) => [
        { type: "TenDaySummaryCaseConference", id: summaryId },
      ],
    }),

    // Query endpoint to get ten-day summaries by patient ID
    getTenDaySummaryCaseConferenceByPatientId: builder.query({
      query: (patientId) => `tendaysummarycaseconference/${patientId}`,
      providesTags: (result, error, summaryId) => [
        { type: "PatientTenDaySummaries", id: summaryId },
      ],
    }),

    // Mutation endpoint to create a new ten-day summary
    createTenDaySummaryCaseConference: builder.mutation({
      query: (summaryData) => ({
        url: "tendaysummarycaseconference",
        method: "POST",
        body: summaryData,
      }),
      invalidatesTags: [
        { type: "TenDaySummaryCaseConference" },
        { type: "PatientTenDaySummaries" },
      ],
    }),

    // Mutation endpoint to update an existing ten-day summary
    updateTenDaySummaryCaseConference: builder.mutation({
      query: ({ summaryId, summaryData }) => ({
        url: `tendaysummarycaseconference/${summaryId}`,
        method: "PUT",
        body: summaryData,
      }),
      invalidatesTags: (result, error, { summaryId }) => [
        { type: "TenDaySummaryCaseConference", id: summaryId },
        { type: "PatientTenDaySummaries", id: result?.summaryId }, // Assuming result includes patientId
      ],
    }),

    // Mutation endpoint to delete a ten-day summary
    deleteTenDaySummaryCaseConference: builder.mutation({
      query: (summaryId) => ({
        url: `tendaysummarycaseconference/${summaryId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, summaryId) => [
        { type: "TenDaySummaryCaseConference", id: summaryId },
        { type: "PatientTenDaySummaries", id: result?.summaryId }, // Assuming result includes patientId
      ],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetTenDaySummaryCaseConferenceByIdQuery,
  useGetTenDaySummariesByPatientIdQuery,
  useCreateTenDaySummaryCaseConferenceMutation,
  useUpdateTenDaySummaryCaseConferenceMutation,
  useDeleteTenDaySummaryCaseConferenceMutation,
} = TenDaySummaryCaseConferenceApi;
