const pagesOption = [
  { label: "Agency Dashboard", value: "/agency-dashboard" },
  { label: "Company Profile", value: "/profile" },
  { label: "Agency Invoice", value: "/agency-invoice" },
  { label: "Payroll", value: "/payroll" },
  { label: "Change Password", value: "/change-password" },
  { label: "Positive Identifications", value: "/positive-identifications" },
  { label: "Notifications", value: "/notification-s" },
  { label: "Permissions", value: "/permissions" },
  { label: "Co-Admins", value: "/coadmins" },
  { label: "Sub-Users", value: "/sub-users" },
  { label: "Billing", value: "/billing" },
  { label: "Providers", value: "/providers" },
  { label: "Create New Provider", value: "/create-new-provider" },
  { label: "Patients", value: "/patient" },
  { label: "Review Email Log", value: "/review-email-log" },
  { label: "Create New Patient", value: "/create-new-patient" },
  { label: "Assign All Individual", value: "/assign-all-individual" },
  { label: "Provider Audit Review", value: "/provider-audit-review" },
  { label: "Caregiver or Staff", value: "/staff" },
  { label: "Admin", value: "/admin" },
  { label: "Guardians", value: "/guardians" },
  { label: "View Outcomes", value: "/view-outcomes" },
  { label: "Support Administrators", value: "/support-administrators" },
  { label: "Healthcare Professional", value: "/healthcare-professional" },
  { label: "Compliance", value: "/compliance" },
  { label: "Location of Service", value: "/location-of-service" },
  { label: "Push Notes", value: "/push-notes" },
  { label: "POS", value: "/pos" },
  { label: "MAR", value: "/mar" },
  { label: "TAR", value: "/tar" },
  { label: "Clock In", value: "/clock-in" },
  { label: "Clock Out", value: "/clock-out" },
  { label: "View Log", value: "/view-log" },
  { label: "Timesheet", value: "/timesheet" },
  { label: "View Assigned Mileage", value: "/view-assigned-mileage" },
  { label: "Add New Mileage", value: "/add-new-mileage" },
  { label: "Mileage Log", value: "/mileage-log" },
  { label: "Folders", value: "/folders" },
  { label: "Set Budget", value: "/set-budget" },
  { label: "Add Community Integration", value: "/add-community-integration" },
  { label: "Community Integration Log", value: "/community-integration-log" },
  { label: "Add Category", value: "/add-category" },
  { label: "Add List of Activity", value: "/add-list-of-activity" },
  { label: "Category", value: "/category" },
  { label: "ADS Location", value: "/ads-location" },
  { label: "List of Activity Log", value: "/list-of-activity-log" },
  { label: "Add Group Activity Documentation", value: "/add-group-activity-documentation" },
  { label: "View Group Documentation Log", value: "/view-group-documentation-log" },
  { label: "ADS Configuration", value: "/ads-configuration" },
  { label: "Attendance Sheet", value: "/attendance-sheet" },
  { label: "Reports", value: "/reports" },
  { label: "Support Employment", value: "/support-employment" },
  { label: "Add Daily Activity", value: "/add-daily-activity" },
  { label: "View Outcome Log", value: "/view-outcome-log" },
  { label: "Manage Unassigned Shift", value: "/manage-unassigned-shift" },
  { label: "Add Shift Summary", value: "/add-shift-summary" },
  { label: "View Shift Summary", value: "/view-shift-summary" },
  { label: "Employee Payroll", value: "/employee-payroll" },
  { label: "Employee Earning", value: "/employee-earning" },
  { label: "Employee Files", value: "/employee-files" },
  { label: "Notices", value: "/employee-notices" },
  { label: "Manage Shift", value: "/manage-shift" },
  { label: "Requested Time Off", value: "/requested-time-off" },
  { label: "Scheduler", value: "/scheduler" },
  { label: "My Vehicles", value: "/my-vehicles" },
  { label: "My Routes", value: "/my-routes" },
  { label: "Add Vehicle Inspection", value: "/add-vehicle-inspection" },
  { label: "View Vehicle Inspection", value: "/view-vehicle-inspection" },
  { label: "Vehicle View Log", value: "/vehicle-view-log" },
  { label: "My Briefcase", value: "/my-briefcase" },
  { label: "Calendars", value: "/calendars" },
  { label: "Shared Events", value: "/shared-events" },
  { label: "Add New Ticket", value: "/add-new-ticket" },
  { label: "Contact Us", value: "/contact-us" },
  { label: "Call Us", value: "/call-us" },
  { label: "Recycle Bin", value: "/recycle-bin" },
  { label: "Payers", value: "/payers" },
  { label: "Create Payers", value: "/create-payers" },
  { label: "Create Physicians", value: "/create-physicians" },
  { label: "Physicians", value: "/physicians" },
  { label: "Clinical Diagnoses", value: "/clinical-diagnoses" },
  { label: "Create Clinical Diagnoses", value: "/create-clinical-diagnoses" },
  { label: "Create Pharmacy", value: "/create-pharmacy" },
  { label: "Pharmacy", value: "/pharmacy" },
  { label: "Contacts", value: "/contacts" },
  { label: "Create Contacts", value: "/create-contacts" },
  { label: "Create Emergency Preparedness", value: "/create-emergency-preparedness" },
  { label: "Emergency Preparedness", value: "/emergency-preparedness" },
  { label: "Advance Directives", value: "/advance-directives" },
  { label: "Create Advance Directives", value: "/create-advance-directives" },
  { label: "Create Referral Information", value: "/create-referral-information" },
  { label: "Referral Information", value: "/referral-information" },
  { label: "User Activation", value: "/user-activation/:token" },
];

export default pagesOption;
