import { rootApi } from "./RootApi";

export const ClockApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getClockById: builder.query({
      query: (clockId) => `clock/${clockId}`,
      providesTags: (result, error, _id) => [{ type: "Clock", id: _id }],
    }),
    createClock: builder.mutation({
      query: (clockData) => ({
        url: "clock",
        method: "POST",
        body: clockData,
      }),
      invalidatesTags: [{ type: "Clock" }],
    }),
    getAllClocks: builder.query({
      query: () => ({
        url: "clock",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Clock" }],
    }),
    updateClock: builder.mutation({
      query: ({ clockId, clockData }) => ({
        url: `clock/${clockId}`,
        method: "PUT",
        body: clockData,
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Clock", id: _id }],
    }),
    deleteClock: builder.mutation({
      query: (clockId) => ({
        url: `clock/${clockId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Clock", id: _id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetClockByIdQuery,
  useCreateClockMutation,
  useGetAllClocksQuery,
  useUpdateClockMutation,
  useDeleteClockMutation,
} = ClockApi;
