import { rootApi } from "./RootApi";

export const ContactApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getContactById: builder.query({
      query: (contactId) => `contacts/${contactId}`,
      providesTags: (result, error, _id) => [{ type: "Contact", id: _id }],
    }),
    createContact: builder.mutation({
      query: (contactData) => ({
        url: "contact/contacts",
        method: "POST",
        body: contactData,
      }),
      invalidatesTags: [{ type: "Contact" }],
    }),
    getAllContacts: builder.query({
      query: () => ({
        url: "contact/contacts",
        method: "GET",
      }),
      providesTags: (result, error) => [{ type: "Contact" }],
    }),
    updateContact: builder.mutation({
      query: ({ contactId, contactData }) => ({
        url: `contact/contacts/${contactId}`,
        method: "PUT",
        body: contactData,
      }),
      invalidatesTags: (result, error, { _id }) => [{ type: "Contact", id: _id }],
    }),
    deleteContact: builder.mutation({
      query: (contactId) => ({
        url: `contact/contacts/${contactId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, contactId) => [{ type: "Contact", id: contactId }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetContactByIdQuery,
  useCreateContactMutation,
  useGetAllContactsQuery,
  useUpdateContactMutation,
  useDeleteContactMutation,
} = ContactApi;
