import { rootApi } from "./RootApi";

export const DirectiveApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getDirectiveById: builder.query({
      query: (directiveId) => `directive/${directiveId}`,
      providesTags: (result, error, directiveId) => [
        { type: "Directive", id: directiveId },
      ],
    }),
    createDirective: builder.mutation({
      query: (directiveData) => ({
        url: "directive",
        method: "POST",
        body: directiveData,
      }),
      invalidatesTags: [{ type: "Directive" }],
    }),
    getAllDirectives: builder.query({
      query: () => ({
        url: "directive",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Directive" }],
    }),
    updateDirective: builder.mutation({
      query: ({ directiveId, directiveData }) => ({
        url: `directive/${directiveId}`,
        method: "PUT",
        body: directiveData,
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Directive", id: _id }],
    }),
    deleteDirective: builder.mutation({
      query: (directiveId) => ({
        url: `directive/${directiveId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Directive", id: _id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetDirectiveByIdQuery,
  useCreateDirectiveMutation,
  useGetAllDirectivesQuery,
  useUpdateDirectiveMutation,
  useDeleteDirectiveMutation,
} = DirectiveApi;
