import { rootApi } from "./RootApi";

export const EmergencyApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getEmergencyById: builder.query({
      query: (emergencyId) => `emergency/${emergencyId}`,
      providesTags: (result, error, _id) => [{ type: "Emergency", id: _id }],
    }),
    getEmergencyByPatientId: builder.query({
      query: (emergencyId) => `emergency/single/${emergencyId}`,
      providesTags: (result, error, _id) => [{ type: "Emergency", id: _id }],
    }),
    createEmergency: builder.mutation({
      query: (emergencyData) => ({
        url: "emergency",
        method: "POST",
        body: emergencyData,
      }),
      invalidatesTags: [{ type: "Emergency" }],
    }),
    getAllEmergencies: builder.query({
      query: () => ({
        url: "emergency",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Emergency" }],
    }),
    updateEmergency: builder.mutation({
      query: ({ emergencyId, emergencyData }) => ({
        url: `emergency/${emergencyId}`,
        method: "PUT",
        body: emergencyData,
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Emergency", id: _id }],
    }),
    deleteEmergency: builder.mutation({
      query: (emergencyId) => ({
        url: `emergency/${emergencyId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Emergency", id: _id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetEmergencyByIdQuery,
  useGetEmergencyByPatientIdQuery,
  useCreateEmergencyMutation,
  useGetAllEmergenciesQuery,
  useUpdateEmergencyMutation,
  useDeleteEmergencyMutation,
} = EmergencyApi;
