import { rootApi } from "./RootApi";

export const InspectionApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getInspectionById: builder.query({
      query: (inspectionId) => `inspections/${inspectionId}`,
      providesTags: (result, error, id) => [{ type: "Inspection", id }],
    }),
    createInspection: builder.mutation({
      query: (inspectionData) => ({
        url: "inspections",
        method: "POST",
        body: inspectionData,
      }),
      invalidatesTags: [{ type: "Inspection", id: "LIST" }],
    }),
    getAllInspections: builder.query({
      query: () => ({
        url: "inspections",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Inspection", id: "LIST" }],
    }),
    updateInspection: builder.mutation({
      query: ({ inspectionId, inspectionData }) => ({
        url: `inspections/${inspectionId}`,
        method: "PUT",
        body: inspectionData,
      }),
      invalidatesTags: (result, error, id) => [{ type: "Inspection", id }],
    }),
    deleteInspection: builder.mutation({
      query: (inspectionId) => ({
        url: `inspections/${inspectionId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, id) => [{ type: "Inspection", id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetInspectionByIdQuery,
  useCreateInspectionMutation,
  useGetAllInspectionsQuery,
  useUpdateInspectionMutation,
  useDeleteInspectionMutation,
} = InspectionApi;
