import { rootApi } from "./RootApi";

export const PharmacyApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getPharmacyById: builder.query({
      query: (pharmacyId) => `pharmacies/${pharmacyId}`,
      providesTags: (result, error, pharmacyId) => [{ type: "Pharmacy", id: pharmacyId }],
    }),
    createPharmacy: builder.mutation({
      query: (pharmacyData) => ({
        url: "pharmacy",
        method: "POST",
        body: pharmacyData,
      }),
      invalidatesTags: [{ type: "Pharmacy" }],
    }),
    getAllPharmacies: builder.query({
      query: () => ({
        url: "pharmacy",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Pharmacy" }],
    }),
    updatePharmacy: builder.mutation({
      query: ({ pharmacyId, pharmacyData }) => ({
        url: `pharmacy/${pharmacyId}`,
        method: "PUT",
        body: pharmacyData,
      }),
      invalidatesTags: (result, error, { pharmacyId }) => [
        { type: "Pharmacy", id: pharmacyId },
      ],
    }),
    deletePharmacy: builder.mutation({
      query: (pharmacyId) => ({
        url: `pharmacy/${pharmacyId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, pharmacyId) => [
        { type: "Pharmacy", id: pharmacyId },
      ],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetPharmacyByIdQuery,
  useCreatePharmacyMutation,
  useGetAllPharmaciesQuery,
  useUpdatePharmacyMutation,
  useDeletePharmacyMutation,
} = PharmacyApi;
