import { rootApi } from "./RootApi";

export const PhysicianApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getPhysicianById: builder.query({
      query: (physicianId) => `physicians/${physicianId}`,
      providesTags: (result, error, _id) => [{ type: "Physician", id: _id }],
    }),
    createPhysician: builder.mutation({
      query: (physicianData) => ({
        url: "physician/create-physician",
        method: "POST",
        body: physicianData,
      }),
      invalidatesTags: [{ type: "Physician" }],
    }),
    getAllPhysicians: builder.query({
      query: () => ({
        url: "physician/physicians",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Physician" }],
    }),
    updatePhysician: builder.mutation({
      query: ({ physicianId, physicianData }) => ({
        url: `physician/physician/${physicianId}`,
        method: "PUT",
        body: physicianData,
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Physician", id: _id }],
    }),
    deletePhysician: builder.mutation({
      query: (physicianId) => ({
        url: `physician/physician/${physicianId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, _id) => [{ type: "Physician", id: _id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetPhysicianByIdQuery,
  useCreatePhysicianMutation,
  useGetAllPhysiciansQuery,
  useUpdatePhysicianMutation,
  useDeletePhysicianMutation,
} = PhysicianApi;
