import { rootApi } from "./RootApi";

export const RouteApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getRouteById: builder.query({
      query: (routeId) => `routes/${routeId}`,
      providesTags: (result, error, id) => [{ type: "Route", id }],
    }),
    createRoute: builder.mutation({
      query: (routeData) => ({
        url: "routes",
        method: "POST",
        body: routeData,
      }),
      invalidatesTags: [{ type: "Route", id: "LIST" }],
    }),
    getAllRoutes: builder.query({
      query: () => ({
        url: "routes",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "Route", id: "LIST" }],
    }),
    updateRoute: builder.mutation({
      query: ({ routeId, routeData }) => ({
        url: `routes/${routeId}`,
        method: "PUT",
        body: routeData,
      }),
      invalidatesTags: (result, error, id) => [{ type: "Route", id }],
    }),
    deleteRoute: builder.mutation({
      query: (routeId) => ({
        url: `routes/${routeId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, id) => [{ type: "Route", id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetRouteByIdQuery,
  useCreateRouteMutation,
  useGetAllRoutesQuery,
  useUpdateRouteMutation,
  useDeleteRouteMutation
} = RouteApi;
