import { rootApi } from "./RootApi";

export const TimeSheetApi = rootApi.injectEndpoints({
  endpoints: (builder) => ({
    getTimeSheetById: builder.query({
      query: (timeSheetId) => `timesheet/${timeSheetId}`,
      providesTags: (result, error, _id) => [{ type: "TimeSheet", id: _id }],
    }),
    createTimeSheet: builder.mutation({
      query: (timeSheetData) => ({
        url: "timesheet",
        method: "POST",
        body: timeSheetData,
      }),
      invalidatesTags: [{ type: "TimeSheet" }],
    }),
    getAllTimeSheets: builder.query({
      query: () => ({
        url: "timesheet",
        method: "GET",
      }),
      providesTags: (result, error, _) => [{ type: "TimeSheet" }],
    }),
    updateTimeSheet: builder.mutation({
      query: ({ timesheetId, timeSheetData }) => ({
        url: `timesheet/${timesheetId}`,
        method: "PUT",
        body: timeSheetData,
      }),
      invalidatesTags: (result, error, _id) => [{ type: "TimeSheet", id: _id }],
    }),
    deleteTimeSheet: builder.mutation({
      query: (timesheetId) => ({
        url: `timesheet/${timesheetId}`,
        method: "DELETE",
      }),
      invalidatesTags: (result, error, _id) => [{ type: "TimeSheet", id: _id }],
    }),
  }),
});

// Export hooks generated by the endpoints
export const {
  useGetTimeSheetByIdQuery,
  useCreateTimeSheetMutation,
  useGetAllTimeSheetsQuery,
  useUpdateTimeSheetMutation,
  useDeleteTimeSheetMutation,
} = TimeSheetApi;
